#pragma once
#define VERSION_MAJOR 1
#define VERSION_MINOR 0
#define VERSION_PATCH 0

#define _STRINGIZE(S) #S
#define STRINGIZE(S)  _STRINGIZE(S)

#define FILE_VERSION_STRING STRINGIZE(VERSION_MAJOR.VERSION_MINOR.VERSION_PATCH)

#define FILE_VERSION_FLAG 0x0L
